from enum import IntEnum


class BitIndex(IntEnum):
    IMMEDIATE_DEATH_UP = 0
    IMMEDIATE_DEATH_RIGHT = 1
    IMMEDIATE_DEATH_DOWN = 2
    IMMEDIATE_DEATH_LEFT = 3

    IMMEDIATE_RED_APPLE_UP = 4
    IMMEDIATE_RED_APPLE_RIGHT = 5
    IMMEDIATE_RED_APPLE_DOWN = 6
    IMMEDIATE_RED_APPLE_LEFT = 7

    GREEN_APPLE_UP = 8
    GREEN_APPLE_RIGHT = 9
    GREEN_APPLE_DOWN = 10
    GREEN_APPLE_LEFT = 11
